const n = (id, kind, label, x, y, category) => ({
  id, type: "infra", position: { x, y }, data: { kind, label, category }
});
const e = (s, t, kind = "request") => ({
  id: `${s}-${t}`, source: s, target: t, type: "traffic", animated: true, data: { kind }
});

export const templates = [
  {
    id: "basic-web", name: "Basic Web App",
    nodes: [
      n("c", "client", "Client", 60, 240, "Client"),
      n("lb", "load-balancer", "Load Balancer", 320, 240, "Network"),
      n("ws", "web-server", "Web Server", 580, 240, "Application"),
      n("db", "postgresql", "PostgreSQL", 840, 240, "Data"),
    ],
    edges: [e("c","lb"), e("lb","ws"), e("ws","db","database")],
  },
  {
    id: "ecommerce", name: "E-Commerce Platform",
    nodes: [
      n("c","client","Client",40,260,"Client"),
      n("cdn","cdn","CDN",260,140,"Network"),
      n("lb","load-balancer","Load Balancer",260,360,"Network"),
      n("gw","api-gateway","API Gateway",500,360,"Network"),
      n("svc","microservice","Catalog Service",740,260,"Application"),
      n("ord","microservice","Order Service",740,460,"Application"),
      n("r","redis","Redis",980,260,"Data"),
      n("db","postgresql","PostgreSQL",980,460,"Data"),
      n("q","kafka","Kafka",1220,360,"Messaging"),
    ],
    edges: [e("c","cdn"),e("c","lb"),e("lb","gw"),e("gw","svc"),e("gw","ord"),e("svc","r","cache"),e("ord","db","database"),e("ord","q","queue")],
  },
  {
    id: "url-shortener", name: "URL Shortener",
    nodes: [
      n("c","client","Client",60,240,"Client"),
      n("lb","load-balancer","LB",300,240,"Network"),
      n("svc","microservice","Shortener API",540,240,"Application"),
      n("r","redis","Redis",780,140,"Data"),
      n("db","postgresql","Postgres",780,340,"Data"),
    ],
    edges: [e("c","lb"),e("lb","svc"),e("svc","r","cache"),e("svc","db","database")],
  },
  {
    id: "chat", name: "Chat Application",
    nodes: [
      n("c","client","Client",40,240,"Client"),
      n("gw","api-gateway","Gateway",260,240,"Network"),
      n("ws","app-server","WebSocket Server",500,240,"Application"),
      n("svc","microservice","Chat Service",740,140,"Application"),
      n("presence","microservice","Presence",740,340,"Application"),
      n("r","redis","Redis",980,140,"Data"),
      n("db","mongodb","MongoDB",980,340,"Data"),
      n("k","kafka","Kafka",1220,240,"Messaging"),
    ],
    edges: [e("c","gw"),e("gw","ws"),e("ws","svc"),e("ws","presence"),e("svc","r","cache"),e("svc","db","database"),e("svc","k","event")],
  },
  {
    id: "netflix", name: "Netflix Architecture",
    nodes: [
      n("c","client","Client",40,260,"Client"),
      n("cdn","cdn","CDN",260,140,"Network"),
      n("gw","api-gateway","API Gateway",260,380,"Network"),
      n("rec","microservice","Recommendations",500,140,"Application"),
      n("play","microservice","Playback",500,380,"Application"),
      n("meta","microservice","Metadata",500,620,"Application"),
      n("r","redis","Redis",760,140,"Data"),
      n("db","mongodb","MongoDB",760,380,"Data"),
      n("es","elasticsearch","Elasticsearch",760,620,"Data"),
      n("k","kafka","Kafka",1000,380,"Messaging"),
    ],
    edges: [e("c","cdn"),e("c","gw"),e("gw","rec"),e("gw","play"),e("gw","meta"),e("rec","r","cache"),e("play","db","database"),e("meta","es","database"),e("play","k","event")],
  },
  { id: "instagram", name: "Instagram Architecture",
    nodes: [
      n("c","client","Client",40,260,"Client"),
      n("cdn","cdn","CDN",260,140,"Network"),
      n("gw","api-gateway","Gateway",260,380,"Network"),
      n("feed","microservice","Feed Service",500,260,"Application"),
      n("media","microservice","Media Service",500,500,"Application"),
      n("r","redis","Redis",760,140,"Data"),
      n("db","postgresql","Postgres",760,380,"Data"),
      n("k","kafka","Kafka",1000,260,"Messaging"),
    ],
    edges: [e("c","cdn"),e("c","gw"),e("gw","feed"),e("gw","media"),e("feed","r","cache"),e("feed","db","database"),e("media","k","event")],
  },
  { id: "uber", name: "Uber Architecture",
    nodes: [
      n("c","mobile","Rider App",40,140,"Client"),
      n("d","mobile","Driver App",40,380,"Client"),
      n("gw","api-gateway","Gateway",260,260,"Network"),
      n("match","microservice","Matching",500,140,"Application"),
      n("trip","microservice","Trip Service",500,380,"Application"),
      n("r","redis","Redis",760,140,"Data"),
      n("db","postgresql","Postgres",760,380,"Data"),
      n("k","kafka","Kafka",1000,260,"Messaging"),
    ],
    edges: [e("c","gw"),e("d","gw"),e("gw","match"),e("gw","trip"),e("match","r","cache"),e("trip","db","database"),e("match","k","event")],
  },
  { id: "whatsapp", name: "WhatsApp Architecture",
    nodes: [
      n("c","mobile","Client",40,240,"Client"),
      n("gw","api-gateway","Gateway",260,240,"Network"),
      n("ws","app-server","WebSocket",500,240,"Application"),
      n("msg","microservice","Message Service",740,240,"Application"),
      n("db","mongodb","MongoDB",980,140,"Data"),
      n("q","queue","Queue",980,340,"Messaging"),
    ],
    edges: [e("c","gw"),e("gw","ws"),e("ws","msg"),e("msg","db","database"),e("msg","q","queue")],
  },
  { id: "youtube", name: "YouTube Architecture",
    nodes: [
      n("c","client","Client",40,260,"Client"),
      n("cdn","cdn","CDN",260,140,"Network"),
      n("gw","api-gateway","Gateway",260,380,"Network"),
      n("up","microservice","Upload",500,140,"Application"),
      n("watch","microservice","Watch Service",500,380,"Application"),
      n("trans","microservice","Transcoder",500,620,"Application"),
      n("db","mysql","MySQL",760,380,"Data"),
      n("es","elasticsearch","Search",760,620,"Data"),
      n("k","kafka","Kafka",1000,380,"Messaging"),
    ],
    edges: [e("c","cdn"),e("c","gw"),e("gw","up"),e("gw","watch"),e("up","trans"),e("watch","db","database"),e("watch","es","database"),e("trans","k","event")],
  },
  { id: "ai-saas", name: "AI SaaS Platform",
    nodes: [
      n("c","client","Client",40,260,"Client"),
      n("gw","api-gateway","Gateway",260,260,"Network"),
      n("orch","microservice","Orchestrator",500,260,"Application"),
      n("llm","llm","LLM Service",740,140,"AI"),
      n("emb","embedding","Embeddings",740,380,"AI"),
      n("vdb","vector-db","Vector DB",980,380,"AI"),
      n("r","redis","Redis",980,140,"Data"),
      n("db","postgresql","Postgres",1220,260,"Data"),
    ],
    edges: [e("c","gw"),e("gw","orch"),e("orch","llm"),e("orch","emb"),e("emb","vdb","database"),e("orch","r","cache"),e("orch","db","database")],
  },
];
